"""add role to users

Revision ID: 48160cd6639b
Revises: cb84c87d7587
Create Date: 2026-04-05 20:01:06.039686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48160cd6639b'
down_revision = 'cb84c87d7587'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.Enum('AH', 'AK', 'AH'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
