"""create categori table

Revision ID: 60d5587ffebc
Revises: 16feafe24b9b
Create Date: 2026-06-06 21:56:23.058824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60d5587ffebc'
down_revision = '16feafe24b9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kategori',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=False),
    sa.Column('jenis', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaksi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_nim', sa.String(length=20), nullable=False),
    sa.Column('kategori_id', sa.Integer(), nullable=False),
    sa.Column('jumlah', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('keterangan', sa.Text(), nullable=True),
    sa.Column('bukti_transaksi', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['kategori_id'], ['kategori.id'], ),
    sa.ForeignKeyConstraint(['user_nim'], ['users.nim'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaksi')
    op.drop_table('kategori')
    # ### end Alembic commands ###
