"""create usatdz

Revision ID: b4f9e4230c3a
Revises: 60d5587ffebc
Create Date: 2026-07-11 21:59:28.165825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4f9e4230c3a'
down_revision = '60d5587ffebc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ustadz',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=False),
    sa.Column('alamat', sa.Text(), nullable=True),
    sa.Column('no_hp', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jadwal_khutbah',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ustadz_id', sa.Integer(), nullable=False),
    sa.Column('tanggal', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ustadz_id'], ['ustadz.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tanggal')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jadwal_khutbah')
    op.drop_table('ustadz')
    # ### end Alembic commands ###
