"""create berita table

Revision ID: bdc1822da665
Revises: ca9f1dccd654
Create Date: 2026-04-27 22:55:06.171746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdc1822da665'
down_revision = 'ca9f1dccd654'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('berita',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_nim', sa.String(length=20), nullable=False),
    sa.Column('judul', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('kategori', sa.String(length=100), nullable=False),
    sa.Column('thumbnail', sa.String(length=255), nullable=True),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('isi', sa.Text(), nullable=False),
    sa.Column('lokasi', sa.String(length=255), nullable=True),
    sa.Column('tanggal_kegiatan', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_nim'], ['users.nim'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('berita')
    # ### end Alembic commands ###
