"""add jurusan dan jenis_kelamin

Revision ID: cb84c87d7587
Revises: ce5b4e38cad4
Create Date: 2026-04-05 18:00:43.815498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb84c87d7587'
down_revision = 'ce5b4e38cad4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jurusan', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('jenis_kelamin', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('jenis_kelamin')
        batch_op.drop_column('jurusan')

    # ### end Alembic commands ###
